import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layoutwrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="scroll-smooth">
        <body className={inter.className}>
        <LayoutWrapper>{children}</LayoutWrapper>
        </body>
        </html>
    );
}
